package GUI;

import Client.ClientHTTPS;
import Client.ClientThread;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diogo
 */
public class FrameLog extends javax.swing.JInternalFrame {
    String PlayerUsername;
    String PlayerPass;
    int PlayerPort;
    Boolean isLog;
    private static ClientThread clientThread;
    /**
     * Creates new form jHome2
     */
    public FrameLog() {
        isLog=false;
        initComponents();
    }

    public String getUsername(){
        return PlayerUsername;
    }
    
    public String getPass(){
        return PlayerPass;
    }
    
    public int getPort(){
        return PlayerPort;
    }
    
    public Boolean isLogg(){
        return isLog;
    }
    
    Boolean checkInputs(){
        if(!checkInputAux(jTextFieldUsername.getText()))return false;
        if(!checkInputAux(jPasswordFieldPass.getPassword()))return false;
        //falta verificação da porta
         PlayerUsername=jTextFieldUsername.getText();
         PlayerPass=arraysToString(jPasswordFieldPass.getPassword());
         PlayerPort=Integer.parseInt(jTextFieldPort.getText());
        int answer_code = ClientHTTPS.login(PlayerUsername, PlayerPass,PlayerPort);
        jInstructions.setText("nAnswer Code: " + answer_code);
        if (answer_code==400) {
            jInstructions.setText("Username and password must have at least 3 characters and port number must be valid.");
            return false;
        } else if (answer_code==401) {
            jInstructions.setText("Incorrect login details or account doesn't exist.");
            return false;
        } else if (answer_code==200) {
            if (clientThread!=null) {
                if (clientThread.isAlive()) {
                    clientThread.close();
                }
            }
            try {
                clientThread = new ClientThread(PlayerPort);
            } catch (IOException ex) {
                Logger.getLogger(FrameLog.class.getName()).log(Level.SEVERE, null, ex);
            }
            clientThread.start();
            return true;
            } else {
            jInstructions.setText("Unexpected error.");
            return false;
        }
    }
    
    String arraysToString(char[] passChar){
        String pass="";
        for(int i=0;i<passChar.length;i++){
            pass+=passChar[i];
        }
        return pass;
    }
    
    Boolean checkInputAux(String input){
        if(input.length()<3){
            jInstructions.setText("Unexpected error.");
            return false;
        }
        else if (input.length() >16){
            jInstructions.setText("Unexpected error.");
            return false;
        }
        else
            return true;
    }
    
    Boolean checkInputAux(char[] input){
        String pass = arraysToString(input);
        if(pass.length()<3 || pass.length()>16){
           jInstructions.setText("Password length should be between 3 and 16");
           return false; 
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangdude = new javax.swing.JLabel();
        hangtitle = new javax.swing.JLabel();
        jInstructions = new javax.swing.JLabel();
        word2discover1 = new javax.swing.JLabel();
        jGo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(631, 388));

        hangdude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hangdude.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diogo\\Documents\\NetBeansProjects\\Hangman\\images\\hang.png")); // NOI18N
        hangdude.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hangtitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hangtitle.setText("HANGMAN.net");

        jInstructions.setBackground(new java.awt.Color(204, 204, 204));
        jInstructions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInstructions.setText("Input data then go!");
        jInstructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        word2discover1.setBackground(new java.awt.Color(204, 204, 204));
        word2discover1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word2discover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word2discover1.setText(" Login ");
        word2discover1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jGo.setText("GO");
        jGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Username:");

        jTextFieldUsername.setText("ex: Hang-4dude20");
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jTextFieldPort.setText("ex: 6969");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Port:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hangdude)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(word2discover1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jGo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordFieldPass)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPort)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(word2discover1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hangdude)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jGo)
                .addGap(18, 18, 18)
                .addComponent(jInstructions)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoActionPerformed
        // TODO add your handling code here:
        isLog = checkInputs();
        if(isLog) jInstructions.setText("Player logged in with success!!! Press Back");
    }//GEN-LAST:event_jGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangdude;
    private javax.swing.JLabel hangtitle;
    private javax.swing.JButton jGo;
    private javax.swing.JLabel jInstructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel word2discover1;
    // End of variables declaration//GEN-END:variables
}
