package GUI;

import Client.ClientHTTPS;
import Game.Player;
import Main.User;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diogo
 */
public class FrameJoin extends javax.swing.JInternalFrame {
    Player localPlayer;
    ArrayList<User> users;
    String[] usernames={"empty"};

    /**
     * Creates new form jHome2
     */
    public FrameJoin() {
        initComponents();
    }
    
    /**
     * Creates new form jHome2
     * @param localPlayer
     */
    public FrameJoin(Player localPlayer1,ArrayList<User> users1) {
        localPlayer = localPlayer1;
        users=users1;
        usernames= updateSTR(users1);
        initComponents();
    }
    
    String[] updateSTR(ArrayList<User> users1){
        String[] ola={"","","","","","","","","","","","","","","",""};
        if(localPlayer.getUsername()=="offline"){
            String[] newe = {"offline","please login","or register"};
            ola = newe;
        }
        else{
            for(int i=0;i<users1.size();i++){
                ola[i]=users1.get(i).getUsername();
            }
        }
        return ola;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hangdude = new javax.swing.JLabel();
        hangtitle = new javax.swing.JLabel();
        jInstructions = new javax.swing.JLabel();
        word2discover1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox();
        jGo = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(631, 388));

        hangdude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hangdude.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diogo\\Documents\\NetBeansProjects\\Hangman\\images\\hang.png")); // NOI18N
        hangdude.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hangdude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hangdudeMouseClicked(evt);
            }
        });

        hangtitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hangtitle.setText("HANGMAN.net");

        jInstructions.setBackground(new java.awt.Color(204, 204, 204));
        jInstructions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInstructions.setText("Choose host then go!");
        jInstructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        word2discover1.setBackground(new java.awt.Color(204, 204, 204));
        word2discover1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word2discover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word2discover1.setText(" Join Game! ");
        word2discover1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hosts list:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(usernames));
        jScrollPane1.setViewportView(jComboBox1);

        jGo.setText("GO");
        jGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hangdude)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(word2discover1)
                        .addGap(141, 141, 141))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGo))
                    .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(word2discover1)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(hangdude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jGo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jInstructions)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hangdudeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hangdudeMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_hangdudeMouseClicked

    private void jGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoActionPerformed
        // TODO add your handling code here:
        if(localPlayer.getUsername()!="offline"){
            if(true)
                jInstructions.setText("\nAnswer Code: " + ClientHTTPS.matchmakingUnpropose(localPlayer.getUsername(), localPlayer.getPass(),String.valueOf(jComboBox1.getSelectedItem())));
            else
                jInstructions.setText("\nAnswer Code: " + ClientHTTPS.matchmakingPropose(localPlayer.getUsername(), localPlayer.getPass(),String.valueOf(jComboBox1.getSelectedItem())));
        }
        jInstructions.setText("Player offline, please login or register");
    }//GEN-LAST:event_jGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hangdude;
    private javax.swing.JLabel hangtitle;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JToggleButton jGo;
    private javax.swing.JLabel jInstructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel word2discover1;
    // End of variables declaration//GEN-END:variables
}
