package GUI;

import Game.Game;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diogo
 */
public final class FrameGameVS extends javax.swing.JInternalFrame {
    Game localGame;
    String line1;
    String line2;
    String line3;
    
    /**
     * Creates new form jHome2
     * @param game1
     */
    public FrameGameVS(Game game1) {
        localGame=game1;
        initComponents();
        updateGuess();
    }
    
    /**
     * Updates guess on screen
     */
    public void updateGuess() {
        //splitGuess();
        String guess = localGame.getGuess();
        if(guess==null) return;
        int indexP=0;
        int indexF;
        int size = guess.length();
        if(size>102){
            indexF=guess.indexOf("   ", 34);
            if(indexF>42){
                indexF=33;
                while(guess.indexOf("   ", indexF)>33){
                    indexF--;
                }
            }
            line1=guess.substring(indexP,indexF+1);
            indexP=indexF;
            indexF=guess.indexOf("   ", indexP+34);
            if(indexF-indexP>42){
                indexF=33+indexP;
                while(guess.indexOf("   ", indexF)>33+indexP){
                    indexF--;
                }
            }
            line2=guess.substring(indexP+1,indexF+1);
            line3=guess.substring(indexF+1);
        }
        else if(size>96){
            indexF=guess.indexOf("   ", 22);
            line1=guess.substring(indexP,indexF+1);
            indexP=indexF;
            indexF=guess.indexOf("   ", indexP+22);
            line2=guess.substring(indexP+1,indexF+1);
            line3=guess.substring(indexF+1);
        }
        else{
            indexF=guess.indexOf("   ", 18);
            line1=guess.substring(indexP,indexF+1);
            indexP=indexF;
            indexF=guess.indexOf("   ", indexP+18);
            line2=guess.substring(indexP+1,indexF+1);
            line3=guess.substring(indexF+1);
        }
        sentence1.setText(line1);
        sentence2.setText(line2);
        sentence3.setText(line3);
        usedLetters.setText(localGame.getUsedLetters());
        if(localGame.getTurn()){
            instructionText.setText("Player one enter letter.");
            jInstructions.setBackground(new java.awt.Color(153, 204, 255));
        }
        else {
            instructionText.setText("Player two enter letter.");
            jInstructions.setBackground(new java.awt.Color(255, 204, 102));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hangdude = new javax.swing.JLabel();
        hangtitle = new javax.swing.JLabel();
        usedLetters = new javax.swing.JLabel();
        nametag1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sentence1 = new javax.swing.JLabel();
        sentence3 = new javax.swing.JLabel();
        sentence2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nametag3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jInstructions = new javax.swing.JPanel();
        instructionText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        inputLetter = new javax.swing.JTextField();
        jEnter = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(631, 392));

        hangdude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hangdude.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diogo\\Documents\\NetBeansProjects\\Hangman\\images\\hang.png")); // NOI18N
        hangdude.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hangtitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hangtitle.setText("HANGMAN.net");

        usedLetters.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usedLetters.setText("Used letters: A B F J U E E E E E E E E E E E E E E E E E E E E ");
        usedLetters.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usedLetters.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        usedLetters.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        nametag1.setBackground(new java.awt.Color(255, 204, 51));
        nametag1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametag1.setText("Player one: ");

        sentence1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sentence1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sentence1.setText("jLabel2");

        sentence3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sentence3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sentence3.setText("jLabel2");

        sentence2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sentence2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sentence2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentence1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(sentence3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sentence2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sentence1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sentence2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sentence3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setText("Alfred");

        nametag3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametag3.setText("Player two: ");

        jTextField3.setBackground(new java.awt.Color(255, 204, 102));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setText("Bernard");

        instructionText.setBackground(new java.awt.Color(204, 204, 204));
        instructionText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionText.setText("Choose an option!");
        instructionText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        instructionText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jInstructionsLayout = new javax.swing.GroupLayout(jInstructions);
        jInstructions.setLayout(jInstructionsLayout);
        jInstructionsLayout.setHorizontalGroup(
            jInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructionText, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jInstructionsLayout.setVerticalGroup(
            jInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inputLetter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputLetterFocusGained(evt);
            }
        });

        jEnter.setText("ENTER");
        jEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEnter)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nametag1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nametag3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usedLetters, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hangdude)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hangdude, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usedLetters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nametag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(nametag3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLetterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputLetterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLetterFocusGained

    private void jEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterActionPerformed
        // TODO add your handling code here:
        // Checkar integridade do input / Checkar resultado
        if(localGame.checkInput(inputLetter.getText())){
           // Actualizar turno
            localGame.saveLetter();
           //Actualizar visuais 
            updateGuess();
        }
        
        
    }//GEN-LAST:event_jEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangdude;
    private javax.swing.JLabel hangtitle;
    private javax.swing.JTextField inputLetter;
    private javax.swing.JLabel instructionText;
    private javax.swing.JButton jEnter;
    private javax.swing.JPanel jInstructions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nametag1;
    private javax.swing.JLabel nametag3;
    private javax.swing.JLabel sentence1;
    private javax.swing.JLabel sentence2;
    private javax.swing.JLabel sentence3;
    private javax.swing.JLabel usedLetters;
    // End of variables declaration//GEN-END:variables
}
