package GUI;


import Client.ClientHTTPS;
import Game.Game;
import Game.Player;
import Main.User;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diogo
 */
public final class MainFrame extends javax.swing.JFrame {
    //game elements
    Game localGame;
    Player localPlayer;
    int dictionaryLenght=10;
    //GUI elements
    FrameHotSeat Fgame;
    FrameInstructions Finstruct;
    FrameJoin Fjoin;
    FrameLog Flog;
    FrameRegister Freg;
    int activeframe=0;
    //conection elements
    Boolean isLogin = false;
    Boolean isHost = false;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initGameElements();
        initFrames();
    }

    /**
     * Initiate Game Elements
     */
    public void initGameElements(){
        localPlayer = new Player("offline");
        localGame = new Game(localPlayer);
    }
    /**
     * Initiate Frames
     */
    public void initFrames(){
        Finstruct = new FrameInstructions();
        Fgame = new FrameHotSeat(localGame);
        Fjoin = new FrameJoin();
        Flog = new FrameLog();
        Freg = new FrameRegister();
    }
    
    /**
     * Read file and set sentence
     * @return 
     * @throws java.io.FileNotFoundException 
     */
    public String getSetence() throws FileNotFoundException, IOException{
        Random r = new Random();
        int R = r.nextInt(dictionaryLenght)+1;
        String sentence= "duh";
        BufferedReader br;
        br = new BufferedReader(new FileReader("dictionary.txt"));
        for(int i=0;i<R;i++){
            sentence = br.readLine();
        }
        return sentence;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlogin1 = new javax.swing.JButton();
        jBack = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hangtitle = new javax.swing.JLabel();
        word2discover1 = new javax.swing.JLabel();
        jlogin = new javax.swing.JButton();
        jJoin = new javax.swing.JButton();
        jCreateS = new javax.swing.JButton();
        jInstructions = new javax.swing.JButton();
        word2discover = new javax.swing.JLabel();
        jRegister = new javax.swing.JButton();

        jlogin1.setText("Login/Logout");
        jlogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogin1MouseClicked(evt);
            }
        });
        jlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogin1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman.net");

        jBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBack.setText("Back");
        jBack.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diogo\\Documents\\NetBeansProjects\\Hangman\\images\\hangman.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        hangtitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hangtitle.setText("HANGMAN.net");

        word2discover1.setBackground(new java.awt.Color(204, 204, 204));
        word2discover1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word2discover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word2discover1.setText(" W_LC_M_! ");
        word2discover1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlogin.setBackground(new java.awt.Color(255, 0, 0));
        jlogin.setText("LOGIN");
        jlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginMouseClicked(evt);
            }
        });
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });

        jJoin.setText("Join game");
        jJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJoinMouseClicked(evt);
            }
        });
        jJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJoinActionPerformed(evt);
            }
        });

        jCreateS.setText("Create Server");
        jCreateS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCreateSMouseClicked(evt);
            }
        });

        jInstructions.setText("Instructions");
        jInstructions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInstructionsMouseClicked(evt);
            }
        });

        word2discover.setBackground(new java.awt.Color(204, 204, 204));
        word2discover.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word2discover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word2discover.setText("Choose an option!");
        word2discover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRegister.setText("Register");
        jRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegisterMouseClicked(evt);
            }
        });
        jRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(word2discover1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCreateS, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(word2discover, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(hangtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(word2discover1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCreateS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(word2discover, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(567, 567, 567)
                    .addComponent(jBack)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jBack)
                    .addContainerGap(341, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        // Go back to previous menu
        jPanel1.setVisible(true);
        if(activeframe==1){
            Flog.setVisible(false);
            if(Flog.isLogg()){
                localGame.setLocal(Flog.getUsername(),Flog.getPass());
                isHost = ClientHTTPS.matchmakingHost(Flog.getUsername(), Flog.getPass());
                jlogin.setText("LOGOUT");
                jlogin.setBackground(new java.awt.Color(51, 255, 51));
            }
        }
        else if(activeframe==2)Fjoin.setVisible(false);
        else if(activeframe==3)Fgame.setVisible(false);
        else if(activeframe==4)Finstruct.setVisible(false);
        else if(activeframe==5) Freg.setVisible(false);
    }//GEN-LAST:event_jBackMouseClicked

    private void jlogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogin1MouseClicked

    private void jlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogin1ActionPerformed

    private void jInstructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInstructionsMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        add(Finstruct);
        Finstruct.setVisible(true);
        activeframe=4;
    }//GEN-LAST:event_jInstructionsMouseClicked

    private void jCreateSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCreateSMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        add(Fgame);
        Fgame.setVisible(true);
        activeframe=3;
    }//GEN-LAST:event_jCreateSMouseClicked

    private void jJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJoinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jJoinActionPerformed

    private void jJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJoinMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        if(!"offline".equals(localPlayer.getUsername())){
            ArrayList<User> users = ClientHTTPS.matchmakingView(localGame.getPlayer().getUsername(), localGame.getPlayer().getPass());
            Fjoin=new FrameJoin(localGame.getPlayer(),users);
        }
        Fjoin=new FrameJoin(localGame.getPlayer(),null);
        add(Fjoin);
        Fjoin.setVisible(true);
        activeframe=2;
    }//GEN-LAST:event_jJoinMouseClicked

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        add(Flog);
        Flog.setVisible(true);
        activeframe=1;
    }//GEN-LAST:event_jloginActionPerformed

    private void jloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //Modo hot-seat para beta test
        //init game elements
        try {
            String s = getSetence();
            localGame.startGame(s, rootPaneCheckingEnabled, "Player 2");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //init visuals
        jPanel1.setVisible(false);
        Fgame= new FrameHotSeat(localGame);
        add(Fgame);
        Fgame.setVisible(true);
        activeframe=3;
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterActionPerformed

    private void jRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        add(Freg);
        Freg.setVisible(true);
        activeframe=5;
        
    }//GEN-LAST:event_jRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangtitle;
    private javax.swing.JLabel jBack;
    private javax.swing.JButton jCreateS;
    private javax.swing.JButton jInstructions;
    private javax.swing.JButton jJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRegister;
    private javax.swing.JButton jlogin;
    private javax.swing.JButton jlogin1;
    private javax.swing.JLabel word2discover;
    private javax.swing.JLabel word2discover1;
    // End of variables declaration//GEN-END:variables
}
